### ISSUE TITLE
pre-commit fails due to absolute paths in .cache

### ISSUE THREAD

**Issue by oatesp** [dadsgarage/dadsgarage#25]
When attempting to run `pre-commit run -a`

I get the error 
`dadsgarage@ae610dca1f1c:~/workdir$ pre-commit run -a
An error has occurred: InvalidManifestError: 
=====> /Users/peteroates/.cache/pre-commit/repomynoeug5/.pre-commit-hooks.yaml does not exist
Check the log at /home/dadsgarage/.cache/pre-commit/pre-commit.log`

It appears that my existing .cache from running pre-commit on my host machine contains absolute paths, causing pre-commit to fail. 

I can get pre-commit to run without mounting the .cache dir, but it is very slow as it sets everything up again. I've looked around but only found examples of pre-commit in Docker similar to this one.

Maybe I'm doing something wrong. Any ideas?

**Comment by RothAndrew** [comment]
Hey Peter, I haven't personally run into this problem yet, but I can definitely see it happening. I would recommend creating a different directory on your host file system to use as the mount folder for the .cache folder inside DG. This will result in your host caching things twice but these days storage is cheap so that is an easy price to pay.

**Comment by RothAndrew** [comment]
@oatesp did you get your issue figured out?

**Comment by oatesp** [comment]
Hi Andrew, thanks for the feedback on this. 

I created a .precommit dir on my host machine and mounted that as .cache in DG, this worked.

Thanks for your help. A really useful docker image :)
